### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by DreamLumine** [xzsk2/TG-EFB-QQ-Docker#24]
输入
`docker run --rm -it --name="gocq" -v $PWD/gocq:/data xzsk2/gocqhttp-docker:latest`
提示
`C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: invalid mode: \Users\Administrator\Documents\cmder\vendor\git-for-windows\data.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.`

更换为
` docker run --rm -it --name="gocq" -v /$PWD/gocq:/data xzsk2/gocqhttp-docker:latest`
错误变成
`New state of 'nil' is invalid.`

**Comment by DreamLumine** [comment]
平台
`Windows7 SP1 X64`
`DockerToolbox-19.03.1`

**Comment by DreamLumine** [comment]
平台
`Windows7 SP1`
`DockerToolbox-19.03.1`

**Comment by sakarie9** [comment]
路径换成 `docker run --rm -it --name="gocq" -v /c/gocq:/data xzsk2/gocqhttp-docker:latest` 之类的试试看？ `/c/`换成自己的盘符和路径

**Comment by DreamLumine** [comment]
> 路径换成 `docker run --rm -it --name="gocq" -v /c/gocq:/data xzsk2/gocqhttp-docker:latest` 之类的试试看？ `/c/`换成自己的盘符和路径

更换为
`docker run --rm -it --name="gocq" -v /d/EFB/gocq:/data xzsk2/gocqhttp-docker:latest`

问题变成
`C:\Program Files\Docker Toolbox\docker.exe: error during connect: Post https://192.168.99.100:2376/v1.40/containers/create?name=gocq: read tcp 198.18.0.1:53785->192.168.99.100:2376: wsarecv: An existing connection was forcibly closed by the remote host.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.`

**Comment by DreamLumine** [comment]
切换到linux以后 出现了另外一个问题
`sleep for 20sec
2022-04-28 13:15:15,683 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:129)
     Initializing slave milkice.qq... 
2022-04-28 13:15:15,919 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:137)
     Slave channel QQ Slave (milkice.qq) # Default profile is initialized. 
2022-04-28 13:15:15,920 [Level 99]: ehforwarderbot.__main__ (__main__.init; __main__.py:142)
     Initializing master blueset.telegram... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 614, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 259, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 68, in request
    return self.request_encode_body(method, url, fields=fields,
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.9/site-packages/telegram/vendor/ptb_urllib3/urllib3/connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.9/site-packages/ehforwarderbot/__main__.py", line 147, in init
    coordinator.add_channel(module(instance_id=instance_id))
  File "/usr/local/lib/python3.9/site-packages/efb_telegram_master/__init__.py", line 127, in __init__
    self.bot_manager: TelegramBotManager = TelegramBotManager(self)
  File "/usr/local/lib/python3.9/site-packages/efb_telegram_master/bot_manager.py", line 174, in __init__
    me = self.updater.bot.get_me()
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 450, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/utils/request.py", line 265, in _request_wrapper
    raise NetworkError(f'urllib3 HTTPError {error}') from error
telegram.error.NetworkError: urllib3 HTTPError EOF occurred in violation of protocol (_ssl.c:1129)`

**Comment by sakarie9** [comment]
看起来像是连不上tg，检查下代理和配置文件

**Comment by DreamLumine** [comment]
> 看起来像是连不上tg，检查下代理和配置文件

谢谢 问题已经解决
