### ISSUE TITLE
使用最新版的go-cqhttp，可以发消息，不能收

### ISSUE THREAD

**Issue by lancer-wang** [xzsk2/TG-EFB-QQ-Docker#39]
2023-06-28 06:27:30,391 [ERROR]: asyncio (base_events.default_exception_handler; base_events.py:1753)
    Task exception was never retrieved
future: <Task finished name='Task-813' coro=<GoCQHttp.__init__.<locals>.handle_msg.<locals>._handle_msg() done, defined at /usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py:191> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 232, in _handle_msg
    main_text, messages, at_dict = await message_elements_wrapper(context, msg_elements, chat)
  File "/usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 177, in message_elements_wrapper
    sub_main_text, sub_messages, sub_at_list = await message_element_wrapper(context, msg_element, chat)
  File "/usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 117, in message_element_wrapper
    msg_type = msg_element["type"]
TypeError: string indices must be integers

**Comment by sakarie9** [comment]
更了 `EFB-Docker`，重拉一下镜像试试

**Comment by lancer-wang** [comment]
> 更了 `EFB-Docker`，重拉一下镜像试试

2023-06-29 01:12:29,799 [ERROR]: asyncio (base_events.default_exception_handler; base_events.py:1753)
    Task exception was never retrieved
future: <Task finished name='Task-79' coro=<GoCQHttp.__init__.<locals>.handle_msg.<locals>._handle_msg() done, defined at /usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py:245> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 314, in _handle_msg
    main_text, messages, at_dict = await message_elements_wrapper(context, msg_elements, chat)
  File "/usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 223, in message_elements_wrapper
    sub_main_text, sub_messages, sub_at_list = await message_element_wrapper(context, msg_element, chat)
  File "/usr/local/lib/python3.9/site-packages/efb_qq_plugin_go_cqhttp/GoCQHttp.py", line 158, in message_element_wrapper
    msg_type = msg_element["type"]
TypeError: string indices must be integers

还是这个报错，能发送，tg那边收不到

**Comment by lancer-wang** [comment]
我用的go-cqhttp的最新版
https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.1.0

**Comment by sbbbsbbb** [comment]
一样，好像很久都不能收到信息了，gocq 那边logs 有看到群消息，但是 tgbot那边没有任何信息
